Fix print exception in minimize_with_adam function
When issuing the following command to render an image with Adam optimizer, encounter the below exception.
python neural_style.py --optimizer adam --style_imgs kandinsky.jpg --content_img  lion.jpg --verbose

exception message is as below:
    print("At iterate {}\tf=  {:.5E}".format(iterations, curr_loss))
TypeError: unsupported format string passed to numpy.ndarray.__format__

It seems the numpy ndarray doesn't support the format arguments.
The code block is changed as below, exception gone.

print("At iterate {}\tf=  {}".format(iterations, curr_loss))

environment:
Window7
Anaconda3(Python-3.5, numpy-1.14.1, tensorflow-1.5.0)